Portfolio: Mobile Menu Milestone
mateoburvi/Portfolio pull request #8
Opened 2023-06-23 23:40 UTC by mateoburvi

# Add Mobile Menu for Portfolio project

In this part of the portfolio, we add:

- CSS for the active menu 
- JS for the interactions on the menu

2023-06-23 23:53 UTC, alexander16108 requested changes
Hi @mateoburvi , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/OdxtuVBggBHFfiAB1K/giphy.gif"/>

## Highlights
✅ Correct use of Flow
✅ Descriptive Pull Request


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-23 23:53 UTC, alexander16108 commented on main.js
> +    // Set menu state
hello there currently when i click on the hamburger menu it doesn't behave as expected. it currently doesn't work at all please fix this little bug and try again 😉

2023-06-24 01:00 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED 🍾✔🎉**
Hello @mateoburvi 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Descriptive PR.
- Good commit messages.
- Correct git-flow.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-24 01:23 UTC, merged

2023-07-27 19:38 UTC, souad988 reviewed
Hi @mateoburvi  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approved2](https://github.com/mateoburvi/Portfolio/assets/59707859/c890d00c-bbbc-4959-a2fb-e8d4076faeaa)


## Highlights
Good PR description
No linter errors
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._